FROM aarch64/ubuntu:xenial-20160809 as l4t-sources

ENV DEBIAN_FRONTEND noninteractive

RUN \
  apt-get update && apt-get install -y wget lbzip2 bzip2 tar && \
  wget https://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/3.2.1/m8u2ki/JetPackL4T_321_b23/Tegra186_Linux_R28.2.1_aarch64.tbz2 && \
  tar -xf Tegra186_Linux_R28.2.1_aarch64.tbz2 && \
  ./Linux_for_Tegra/apply_binaries.sh -r / && \
  rm Tegra186_Linux_R28.2.1_aarch64.tbz2 && \
  echo "/usr/lib/aarch64-linux-gnu/tegra" > /etc/ld.so.conf.d/nvidia-tegra.conf && ldconfig


# some precompiled libs need old libgbm, as default libgbm1 18.X will not find drmGetDevice2 or similar
RUN \
  apt-get install -y gstreamer1.0-tools \
  gstreamer1.0-alsa \
  gstreamer1.0-plugins-base \
  gstreamer1.0-plugins-good \
  gstreamer1.0-plugins-bad \
  gstreamer1.0-plugins-ugly \
  gstreamer1.0-libav \
  libgstreamer-plugins-good1.0-dev \
  libgstreamer-plugins-bad1.0-dev \
  libgstreamer1.0-dev \
  libgstreamer-plugins-base1.0-dev && \
  apt-get install -y --allow-downgrades libgbm1=11.2.0-1ubuntu2 && \
  ln -s /usr/lib/aarch64-linux-gnu/tegra-egl/libEGL.so.1 /usr/lib/aarch64-linux-gnu/libEGL.so.1

RUN apt-get install -y gstreamer1.0-plugins-bad xorg
ENV LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/tegra

ENV UDEV=1
ENV INITSYSTEM on

CMD ["bash"]


